[package]
name = "fastlio-estimator"
version.workspace = true
edition.workspace = true

[dependencies]
fastlio-types = { path = "../fastlio-types" }
fastlio-map = { path = "../fastlio-map" }
nalgebra = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
slotmap = { workspace = true }
