[package]
name = "fastlio-pipeline"
version.workspace = true
edition.workspace = true

[dependencies]
fastlio-types = { path = "../fastlio-types" }
fastlio-imu = { path = "../fastlio-imu" }
anyhow = { workspace = true }
nalgebra = { workspace = true }
camino = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
